BookList_Razor/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

BookList_Razor/Pages/BookList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList_Razor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages.BookList
{
    public class CreateModel : PageModel
    {
        private ApplicationDbContext _db;

        [TempData]
        public string Message { get; set; }

        public CreateModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _db.Books.Add(Book);
            await _db.SaveChangesAsync();
            Message = "New Book added succesfully";
            return RedirectToPage("Index");
        }
    }
}

BookList_Razor/Pages/BookList/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList_Razor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BookList_Razor.Pages.BookList
{
    public class DetailsModel : PageModel
    {
        private ApplicationDbContext _db;

        public DetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        public void OnGet(int id)
        {
            Book = _db.Books.Find(id);
        }

    }
}

BookList_Razor/Pages/BookList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList_Razor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages.BookList
{
    public class EditModel : PageModel
    {
        private ApplicationDbContext _db;

        public EditModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Book Book { get; set; }

        [TempData]
        public string Message { get; set; }

        public void OnGet(int id)
        {
            Book = _db.Books.Find(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var bookInDb = _db.Books.Find(Book.Id);
                bookInDb.ISBN = Book.ISBN;
                bookInDb.Title = Book.Title;
                bookInDb.Author = Book.Author;
                bookInDb.Price = Book.Price;
                bookInDb.Avaibility = Book.Avaibility;

                await _db.SaveChangesAsync();
                Message = "Book updated successfully";

                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }
    }
}

BookList_Razor/Pages/BookList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookList_Razor.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace BookList_Razor.Pages.BookList
{
    public class IndexModel : PageModel
    {
        private ApplicationDbContext _db;

        [TempData]
        public string Message { get; set; }

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Book> Books { get; set; }

        public async Task OnGet()
        {
            Books = await _db.Books.ToListAsync();
        }

        public async Task<IActionResult> OnPostDelete(int id)
        {
            var book = _db.Books.Find(id);
            _db.Books.Remove(book);
            await _db.SaveChangesAsync();

            Message = "Book Deleted Successfully";

            return RedirectToPage();
        }
    }
}

BookList_Razor/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

BookList_Razor/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BookList_Razor/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BookList_Razor.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

BookList_Razor/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

BookList_Razor/Pages/BookList/Create.cshtml
@page
@model CreateModel
@{
}

<br />
<h2>Create Book</h2>
<hr />
<div style="border: 1px solid #bbb9b9; border-radius: 5px;">
    <form method="post">
        <div class="row" style="padding-left: 50px; padding-top: 30px;">
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.ISBN"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.ISBN" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Title"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Title" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Author"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Author" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Price"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Price" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Avaibility"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Avaibility" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Avaibility" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-sm" />
                <a asp-page="Index" class="btn btn-success btn-sm">Back to List</a>
            </div>
        </div>
    </form>
</div>

BookList_Razor/Pages/BookList/Details.cshtml
@page
@model DetailsModel
@{
}

<br />
<h2>Details</h2>
<hr />
<div style="border: 1px solid #bbb9b9; border-radius: 5px;">
        <div class="row" style="padding-left: 50px; padding-top: 30px;">
            <input type="hidden" asp-for="Book.Id" disabled/>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.ISBN"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.ISBN" class="form-control" disabled/>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Title"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Title" class="form-control" disabled/>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Author"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Author" class="form-control" disabled/>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Price"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Price" class="form-control" disabled/>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Avaibility"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Avaibility" class="form-control" disabled/>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <a asp-page="Edit" asp-route-id="@Model.Book.Id" class="btn btn-sm btn-primary">Edit</a>
                <a asp-page="Index" class="btn btn-success btn-sm">Back to List</a>
            </div>
        </div>
</div>

BookList_Razor/Pages/BookList/Edit.cshtml
@page
@model EditModel
@{
}

<br />
<h2>Edit Book</h2>
<hr />
<div style="border: 1px solid #bbb9b9; border-radius: 5px;">
    <form method="post">
        <div class="row" style="padding-left: 50px; padding-top: 30px;">
            <input type="hidden" asp-for="Book.Id" />
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.ISBN"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.ISBN" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.ISBN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Title"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Title" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Author"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Author" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Author" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Price"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Price" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-1">
                        <label asp-for="Book.Avaibility"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Book.Avaibility" class="form-control" />
                    </div>
                </div>
                <span asp-validation-for="Book.Avaibility" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary btn-sm" />
                <a asp-page="Index" class="btn btn-success btn-sm">Back to List</a>
            </div>
        </div>
    </form>
</div>

BookList_Razor/Pages/BookList/Index.cshtml
@page "{id:int?}/{handler?}"
@model IndexModel
@{
}

<br />
<h2>Book list</h2>
<hr />

@if (Model.Message != null)
{ 
    <div class="alert alert-info alert-dismissable" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        @Model.Message
    </div>
}

<a asp-page="Create" class="btn btn-primary">Create new Book</a>

@if (Model.Books.Count() > 0)
{
    <form method="post">
        <div>
            <br />
            <table class="table table-condensed table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(m => m.Books.FirstOrDefault().ISBN)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Books.FirstOrDefault().Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Books.FirstOrDefault().Author)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Books.FirstOrDefault().Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.Books.FirstOrDefault().Avaibility)
                    </th>
                    <th>

                    </th>
                </tr>
                @foreach(var item in Model.Books)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.ISBN)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Author)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Avaibility)
                    </td>
                    <td>
                        <a asp-page="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-success">Edit</a>
                        <a asp-page="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Details</a>
                        <button asp-page-handler="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</button>
                    </td>
                </tr>

                }
            </table>
        </div>
    </form>
}
else
{ 
    <p>No books found</p>
}

BookList_Razor/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BookList_Razor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

BookList_Razor/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookList_Razor</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">BookList_Razor</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/BookList/Index">Book</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - BookList_Razor</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>